#!/usr/bin/env bash

set -e

IN=$1
OUT=$2

TOOLS_DIR="$(cd "$(dirname "$0")"/../../tools && pwd -P)"

echo "Compiling $IN with zksolc"

"$TOOLS_DIR/bin/zksolc" -O3 \
    --bin --metadata-literal --metadata-hash none \
    --evm-version paris \
    -o $OUT --overwrite \
    $IN
