#!/usr/bin/env bash

set -e

echo " ┌─────────────────────────────┐"
echo " │   Compiling Link Token...   │"
echo " │         with zksolc         │"
echo " └─────────────────────────────┘"

CONTRACT=$1

../tools/bin/zksolc -O3 \
    --bin --metadata-literal --metadata-hash none \
    --evm-version paris \
    -o zksolc/"$CONTRACT" --overwrite \
    src/v0.8/"$CONTRACT".sol
