// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	capabilities "github.com/smartcontractkit/chainlink-common/pkg/capabilities"

	mock "github.com/stretchr/testify/mock"
)

// DonNotifyWaitSubscriber is an autogenerated mock type for the DonNotifyWaitSubscriber type
type DonNotifyWaitSubscriber struct {
	mock.Mock
}

type DonNotifyWaitSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *DonNotifyWaitSubscriber) EXPECT() *DonNotifyWaitSubscriber_Expecter {
	return &DonNotifyWaitSubscriber_Expecter{mock: &_m.Mock}
}

// NotifyDonSet provides a mock function with given fields: don
func (_m *DonNotifyWaitSubscriber) NotifyDonSet(don capabilities.DON) {
	_m.Called(don)
}

// DonNotifyWaitSubscriber_NotifyDonSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDonSet'
type DonNotifyWaitSubscriber_NotifyDonSet_Call struct {
	*mock.Call
}

// NotifyDonSet is a helper method to define mock.On call
//   - don capabilities.DON
func (_e *DonNotifyWaitSubscriber_Expecter) NotifyDonSet(don interface{}) *DonNotifyWaitSubscriber_NotifyDonSet_Call {
	return &DonNotifyWaitSubscriber_NotifyDonSet_Call{Call: _e.mock.On("NotifyDonSet", don)}
}

func (_c *DonNotifyWaitSubscriber_NotifyDonSet_Call) Run(run func(don capabilities.DON)) *DonNotifyWaitSubscriber_NotifyDonSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(capabilities.DON))
	})
	return _c
}

func (_c *DonNotifyWaitSubscriber_NotifyDonSet_Call) Return() *DonNotifyWaitSubscriber_NotifyDonSet_Call {
	_c.Call.Return()
	return _c
}

func (_c *DonNotifyWaitSubscriber_NotifyDonSet_Call) RunAndReturn(run func(capabilities.DON)) *DonNotifyWaitSubscriber_NotifyDonSet_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx
func (_m *DonNotifyWaitSubscriber) Subscribe(ctx context.Context) (<-chan capabilities.DON, func(), error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan capabilities.DON
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan capabilities.DON, func(), error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan capabilities.DON); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan capabilities.DON)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) func()); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DonNotifyWaitSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type DonNotifyWaitSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DonNotifyWaitSubscriber_Expecter) Subscribe(ctx interface{}) *DonNotifyWaitSubscriber_Subscribe_Call {
	return &DonNotifyWaitSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx)}
}

func (_c *DonNotifyWaitSubscriber_Subscribe_Call) Run(run func(ctx context.Context)) *DonNotifyWaitSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DonNotifyWaitSubscriber_Subscribe_Call) Return(_a0 <-chan capabilities.DON, _a1 func(), _a2 error) *DonNotifyWaitSubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DonNotifyWaitSubscriber_Subscribe_Call) RunAndReturn(run func(context.Context) (<-chan capabilities.DON, func(), error)) *DonNotifyWaitSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForDon provides a mock function with given fields: ctx
func (_m *DonNotifyWaitSubscriber) WaitForDon(ctx context.Context) (capabilities.DON, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitForDon")
	}

	var r0 capabilities.DON
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (capabilities.DON, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) capabilities.DON); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(capabilities.DON)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DonNotifyWaitSubscriber_WaitForDon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForDon'
type DonNotifyWaitSubscriber_WaitForDon_Call struct {
	*mock.Call
}

// WaitForDon is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DonNotifyWaitSubscriber_Expecter) WaitForDon(ctx interface{}) *DonNotifyWaitSubscriber_WaitForDon_Call {
	return &DonNotifyWaitSubscriber_WaitForDon_Call{Call: _e.mock.On("WaitForDon", ctx)}
}

func (_c *DonNotifyWaitSubscriber_WaitForDon_Call) Run(run func(ctx context.Context)) *DonNotifyWaitSubscriber_WaitForDon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DonNotifyWaitSubscriber_WaitForDon_Call) Return(_a0 capabilities.DON, _a1 error) *DonNotifyWaitSubscriber_WaitForDon_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DonNotifyWaitSubscriber_WaitForDon_Call) RunAndReturn(run func(context.Context) (capabilities.DON, error)) *DonNotifyWaitSubscriber_WaitForDon_Call {
	_c.Call.Return(run)
	return _c
}

// NewDonNotifyWaitSubscriber creates a new instance of DonNotifyWaitSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDonNotifyWaitSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *DonNotifyWaitSubscriber {
	mock := &DonNotifyWaitSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
