runners:
  # default runners (https://runs-on.com/runners/linux/):
  # - 1cpu-linux-x64
  # - 2cpu-linux-x64
  # - 4cpu-linux-x64
  # - 8cpu-linux-x64
  # - 16cpu-linux-x64
  # - 32cpu-linux-x64
  # - 48cpu-linux-x64
  # - 64cpu-linux-x64

  # Used for go-mod-cache.yml
  standard-x64:
    cpu: [4, 8]
    ram: [8, 32]
    family: ["c7", "m7", "c6", "m6", "c5", "m5"]
    image: ubuntu24-full-x64
    disk: large
    extras: [ "s3-cache"]

  # 8-16 core, ssd-backed instances.
  # For general purpose CI tasks reliant on fast IOPS.
  medium-ssd-backed-x64:
    cpu: [8, 16]
    ram: [16, 128]
    family: ["c6id", "c5ad", "m6id", "m6idn", "m5d", "m5dn", "m5ad", "r5ad"]
    image: ubuntu22-full-x64
    extras: [ "s3-cache"]

  # 32-64 core, ssd-backed instances.
  # Unit tests require fast IOPS, which EBS-backed instances cannot provide.
  ci-core-unit-tests-x64:
    cpu: [32, 64]
    ram: [64, 256]
    family: ["c6id", "c5ad", "m6id", "m6idn", "m5d", "m5dn", "m5ad", "r5ad"]
    image: ubuntu22-full-x64
    extras: [ "s3-cache"]

  # 64-128 core runner for race tests.
  # large disk = 80GB EBS volume, as these are not SSD backed and the default (40GB) is not enough.
  ci-core-race-tests-x64:
    cpu: [64, 128]
    ram: [128, 256]
    family: ["c7", "m7"]
    disk: large
    image: ubuntu22-full-x64
    extras: [ "s3-cache"]
