name: CI lint for Golang
description: Runs CI lint for Golang
inputs:
  go-directory:
    description: Go directory to run commands from
    default: "."
  # setup-go inputs
  only-modules:
    description: Set to 'true' to only cache modules
    default: "false"
  cache-version:
    description: Set this to cache bust
    default: "1"
  go-version-file:
    description: Set where the go version file is located at
    default: "go.mod"
  go-module-file:
    description: Set where the go module file is located at
    default: "go.sum"
  fix-issues:
    description: If set to "true", will attempt to fix found issues and commit any resulting changes
    required: false
    default: "false"
  gati-role-arn:
    description: ARN of the GATI role to assume for GitHub token. Needed to commit fixes to the PR.
    required: false
  gati-lambda-url:
    description: URL of the GATI Lambda function to get the GitHub token. Needed to commit fixes to the PR.
    required: false
  gati-region:
    description: AWS region for the GATI Lambda function
    default: "us-west-2"

outputs:
  golang-report-artifact-url:
    description: The URL to the uploaded artifact
    value: ${{ steps.upload-artifact.outputs.artifact-url }}

runs:
  using: composite
  steps:
    - name: Checkout repo (full)
      uses: actions/checkout@v4
      # Only do a full checkout on merge_groups
      if: github.event_name == 'merge_group'
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Checkout repo
      uses: actions/checkout@v4
      if: github.event_name != 'merge_group'
      with:
        persist-credentials: false
        fetch-depth: 1

    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        only-modules: ${{ inputs.only-modules }}
        cache-version: ${{ inputs.cache-version }}
        go-version-file: ${{ inputs.go-version-file }}
        go-module-file: ${{ inputs.go-module-file }}

    - name: Touching core/web/assets/index.html
      shell: bash
      run: mkdir -p core/web/assets && touch core/web/assets/index.html

    - name: Set Golangci-lint working directory
      shell: bash
      id: set-working-directory
      # XXX: Don't use `.` default working directory here due to issues with the golangci-lint-action.
      run: |
        if [ "${{ inputs.go-directory }}" == "." ]; then
          echo "golangci-lint-working-directory=" >> $GITHUB_OUTPUT
        else
          echo "golangci-lint-working-directory=${{ inputs.go-directory }}/" >> $GITHUB_OUTPUT
        fi

    # If asked to fix issues, set up Git user and GitHub token to make the commit.
    - name: Set up Git user to commit fixes
      if: ${{ inputs.fix-issues }}
      shell: bash
      run: |
        if [ -z "${{ inputs.gati-role-arn }}" ] || [ -z "${{ inputs.gati-lambda-url }}" ] || [ -z "${{ inputs.gati-region }}" ]; then
          echo "ERROR: fix-issues=${{ inputs.fix-issues }}: Unable to commit linting fixes to the PR: GATI inputs are not set."
          exit 1
        fi

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Setup GitHub Token to commit fixes
      if: ${{ inputs.fix-issues }}
      id: setup-github-token
      uses: smartcontractkit/.github/actions/setup-github-token@ef78fa97bf3c77de6563db1175422703e9e6674f # setup-github-token@0.1.2
      with:
        aws-role-arn: ${{ inputs.gati-role-arn }}
        aws-lambda-url: ${{ inputs.gati-lambda-url }}
        aws-region: ${{ inputs.gati-region }}
        aws-role-duration-seconds: "1800"

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      env:
        # golangci-lint runs with absolute path mode: --path-mode=abs
        REPORT_PATH: ${{ github.workspace }}/${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.xml
      with:
        version: v2.2.1
        only-new-issues: true
        args: --output.checkstyle.path=${{ env.REPORT_PATH }} ${{ inputs.fix-issues == 'true' && '--fix' || '' }}
        working-directory: ${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}

    - name: Commit golangci-lint fixes
      if: ${{ inputs.fix-issues }}
      uses: planetscale/ghcommit-action@322be9669498a4be9ce66efc1169f8f43f6bd883 # v0.2.17
      with:
        commit_message: "🤖 golangci-lint fixes"
        repo: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{steps.setup-github-token.outputs.access-token}}

    - name: Print Golangci-lint report results
      if: failure()
      shell: bash
      run: |
        cat ./${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.xml

    - name: Comment on PR if Lint Fails
      shell: bash
      if: ${{ failure() && inputs.fix-issues != 'true' }}
      env:
        GITHUB_TOKEN: ${{ steps.setup-github-token.outputs.access-token }}
        GH_TOKEN: ${{ steps.setup-github-token.outputs.access-token }}
      run: gh pr comment ${{ github.event.pull_request.number }} --body 'If you want me to try to automatically fix your linting issues, you can add the `auto-fix` label to the PR.' -R ${{ github.repository }}

      # Get a valid name for the upload-artifact step.
      # Avoid error: `The artifact name is not valid: <path>/<to>/<artifact>/` caused by `/`.
      # Remove trailing `/` from the directory name: `core/scripts/` -> `core/scripts`.
      # Replace remaining `/` with `-`: `core/scripts` -> `core-scripts`.
      # Assign `root` if the directory name is empty (ref: step.id: set-working-directory).
    - name: Get valid suffix for artifact name
      if: always()
      id: suffix
      shell: bash
      run: |
        go_directory=${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}
        echo "Validating if directory name '$go_directory' is empty or has slashes"

        if [[ $go_directory == *\/* ]]; then
            suffix=$(echo "$go_directory" | sed 's:\/$::' | tr '/' '-')
            echo "Directory name with slashes '$go_directory' updated to a valid artifact suffix '$suffix'"
        elif [[ $go_directory == "" ]]; then
          suffix="root"
          echo "Root directory (empty string) updated to a valid artifact suffix '$suffix'"
        else
          suffix="$go_directory"
          echo "Directory name is valid for the artifact suffix: '$suffix'"
        fi

        echo "suffix=${suffix}" >> $GITHUB_OUTPUT

    - name: Store Golangci-lint report artifact
      if: always()
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        # Use a unique suffix for each lint report artifact to avoid duplication errors
        name: golangci-lint-report-${{ steps.suffix.outputs.suffix }}
        # N/B: value may be empty (no slash) OR `<path>/<to>/<module>/` (with slash tat the end)
        path: ./${{ steps.set-working-directory.outputs.golangci-lint-working-directory }}golangci-lint-report.xml
