name: Setup CI Core Tests
description: Shared setup steps for ci-core
inputs:
  test-suite:
    description: |
      The test suite's name
    required: true

  evm-ref-override:
    description: |
      Overrides the evm/relayer dependency version
    required: false

  db-url:
    description: |
      The expected database URL
    required: true

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: ./.github/actions/setup-nodejs
      with:
        prod: "true"

    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        # only restore for now
        restore-build-cache-only: "true"
        build-cache-version: ${{ inputs.test-suite }}

    - name: Replace chainlink-evm deps
      if: ${{ inputs.evm-ref-override != ''}}
      shell: bash
      run: go get github.com/smartcontractkit/chainlink-integrations/evm/relayer@${{ inputs.evm-ref-override }}

    - name: Setup Solana
      uses: ./.github/actions/setup-solana

    - name: Setup wasmd
      uses: ./.github/actions/setup-wasmd

    - name: Setup Postgres
      uses: ./.github/actions/setup-postgres

    - name: Touching core/web/assets/index.html
      shell: bash
      run: mkdir -p core/web/assets && touch core/web/assets/index.html

    - name: Download Go vendor packages
      shell: bash
      run: go mod download

    - name: Go Mod Download (deployment)
      if: ${{ matrix.type.test-suite == 'ccip-deployment' }}
      shell: bash
      working-directory: "./deployment"
      run: go mod download

    - name: Build binary
      shell: bash
      run: go build -o chainlink.test .

    - name: Setup DB
      shell: bash
      run: ./chainlink.test local db preparetest
      env:
        CL_DATABASE_URL: ${{ inputs.db-url }}

    - name: Install LOOP Plugins
      shell: bash
      run: |
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-feeds)
        go install ./cmd/chainlink-feeds
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-data-streams)
        go install ./mercury/cmd/chainlink-mercury
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-solana)
        go install ./pkg/solana/cmd/chainlink-solana
        popd
        pushd $(go list -m -f "{{.Dir}}" github.com/smartcontractkit/chainlink-starknet/relayer)
        go install ./pkg/chainlink/cmd/chainlink-starknet
        popd

