package v2

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	sdkpb "github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2/pb"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/wasm/host"
)

var _ host.CapabilityExecutor = (*CapabilityExecutor)(nil)

type CapabilityExecutor struct {
	*Engine
	Id string
}

// CallCapability handles requests generated by the wasm guest
func (e *CapabilityExecutor) CallCapability(ctx context.Context, request *sdkpb.CapabilityRequest) (*sdkpb.CapabilityResponse, error) {
	select {
	case e.capCallsSemaphore <- struct{}{}: // block if too many concurrent capability calls
	case <-ctx.Done():
		return nil, ctx.Err()
	}
	defer func() { <-e.capCallsSemaphore }()

	// TODO (CAPPL-735): use request.Metadata.WorkflowExecutionId to associate the call with a specific execution
	capability, err := e.cfg.CapRegistry.GetExecutable(ctx, request.Id)
	if err != nil {
		return nil, fmt.Errorf("trigger capability not found: %w", err)
	}

	capReq := capabilities.CapabilityRequest{
		Payload:      request.Payload,
		Method:       request.Method,
		CapabilityId: request.Id,
		Metadata: capabilities.RequestMetadata{
			WorkflowExecutionID: e.Id,
		},
	}

	// TODO(CAPPL-737): run with a timeout
	capResp, err := capability.Execute(ctx, capReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute capability: %w", err)
	}
	return &sdkpb.CapabilityResponse{
		Response: &sdkpb.CapabilityResponse_Payload{
			Payload: capResp.Payload,
		},
	}, nil
}
