name: Solana build contracts
description: Build Solana contracts

runs:
  using: composite
  steps:
    - name: Checkout chainlink-ccip
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
        repository: smartcontractkit/chainlink-ccip
        path: chainlink-ccip
    - name: Get Anchor Version
      id: get_anchor_version
      shell: bash
      run: |
        cd chainlink-ccip/chains/solana
        anchor=$(make anchor_version)
        echo "ANCHOR_VERSION=${anchor}" >> $GITHUB_ENV
    - name: cache docker build image
      id: cache-image
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        lookup-only: true
        path: chains/solana/contracts/docker-build.tar
        key: ${{ runner.os }}-solana-build-${{ env.ANCHOR_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo target dir
      id: cache-target
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        lookup-only: true
        path: chains/solana/contracts/target
        key: ${{ runner.os }}-solana-contract-artifacts-${{ hashFiles('**/Cargo.lock') }}
    - name: build & save image
      if: steps.cache-image.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd chainlink-ccip/chains/solana/contracts
        docker buildx build . -t ccip-solana:build --build-arg ANCHOR_CLI=${{ env.ANCHOR_VERSION }}
        docker save -o docker-build.tar ccip-solana
    - name: build & save contract compilation artifacts
      if: steps.cache-target.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd chainlink-ccip/chains/solana
        docker run -v "$(pwd)/contracts":/solana/contracts ccip-solana:build bash -c "\
          set -eoux pipefail &&\
          RUSTUP_HOME=\"/root/.rustup\" &&\
          FORCE_COLOR=1 &&\
          cd /solana/contracts &&\
          anchor build &&\
          chmod -R 755 ./target"
    - name: move built contracts to test folder
      shell: bash
      run: |
        mkdir -p chainlink-ccip/chains/solana/tests/contracts
        cp -r chainlink-ccip/chains/solana/contracts/target/*.so deployment/ccip/changeset/internal/solana_contracts
