dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
packages:
  github.com/smartcontractkit/chainlink-deployments-framework/deployment:
    config:
      srcpkg: github.com/smartcontractkit/chainlink-deployments-framework/deployment
      mockname: "Mock{{ .InterfaceName }}"
      filename: offchain_client_mock.go
      inpackage: true
      dir: ./mocks/
    interfaces:
      OffchainClient:

  github.com/smartcontractkit/chainlink-evm/gethwrappers/workflow/generated/workflow_registry_wrapper:
    config:
      dir: common/view/v1_0/mocks/
      filename: workflow_registry_interface.go
      outpkg: mocks
    interfaces:
      WorkflowRegistryInterface:

  github.com/smartcontractkit/chainlink-evm/gethwrappers/workflow/llo-feeds/generated/fee_manager_v0_5_0/fee_manager_v0_5_0:
    config:
      dir: data-streams/view/v0_5/mocks/
      filename: fee_manager_mock.go
      outpkg: mocks
    interfaces:
      FeeManagerInterface:
