// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	vault "github.com/smartcontractkit/chainlink-common/pkg/capabilities/actions/vault"
	pluginsvault "github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/vault"
	mock "github.com/stretchr/testify/mock"
)

// SecretsService is an autogenerated mock type for the SecretsService type
type SecretsService struct {
	mock.Mock
}

type SecretsService_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretsService) EXPECT() *SecretsService_Expecter {
	return &SecretsService_Expecter{mock: &_m.Mock}
}

// CreateSecrets provides a mock function with given fields: ctx, request
func (_m *SecretsService) CreateSecrets(ctx context.Context, request *vault.CreateSecretsRequest) (*pluginsvault.Response, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecrets")
	}

	var r0 *pluginsvault.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *vault.CreateSecretsRequest) (*pluginsvault.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *vault.CreateSecretsRequest) *pluginsvault.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pluginsvault.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *vault.CreateSecretsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretsService_CreateSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecrets'
type SecretsService_CreateSecrets_Call struct {
	*mock.Call
}

// CreateSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - request *vault.CreateSecretsRequest
func (_e *SecretsService_Expecter) CreateSecrets(ctx interface{}, request interface{}) *SecretsService_CreateSecrets_Call {
	return &SecretsService_CreateSecrets_Call{Call: _e.mock.On("CreateSecrets", ctx, request)}
}

func (_c *SecretsService_CreateSecrets_Call) Run(run func(ctx context.Context, request *vault.CreateSecretsRequest)) *SecretsService_CreateSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.CreateSecretsRequest))
	})
	return _c
}

func (_c *SecretsService_CreateSecrets_Call) Return(_a0 *pluginsvault.Response, _a1 error) *SecretsService_CreateSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecretsService_CreateSecrets_Call) RunAndReturn(run func(context.Context, *vault.CreateSecretsRequest) (*pluginsvault.Response, error)) *SecretsService_CreateSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecretsService creates a new instance of SecretsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsService {
	mock := &SecretsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
