name: Setup CRE E2E Test Dependencies
description: Setup dependencies for CRE E2E tests with efficient caching

inputs:

  cre-cli-version:
    description: Version of the CRE CLI to use
    default: "v0.2.0"
  capability-version:
    description: Version of the capability to use
    default: "v1.0.2-alpha"
  capability-names:
    description: Comma-separated list of capability names to use
    default: "cron"

  # GATI Inputs
  gati-role-arn:
    description: ARN of the GATI role to assume for GitHub token
    required: true
  gati-lambda-url:
    description: URL of the GATI Lambda function to get the GitHub token
    required: true
  gati-region:
    description: AWS region for the GATI Lambda function
    default: "us-west-2"

env:
  DOWNLOAD_PATH: ${{ github.workspace }}/system-tests/binaries-deps
  EXPECTED_PATH: ${{ github.workspace }}system-tests/tests/smoke/cre

runs:
  using: composite
  steps:

    - name: Setup cache directory and key
      id: setup-cache-dir-key
      shell: bash
      env:
        CRE_CLI_VERSION: ${{ inputs.cre-cli-version }}
        CAPABILITY_NAMES: ${{ inputs.capability-names }}
        CAPABILITY_VERSION: ${{ inputs.capability-version }}
      run: |
        mkdir -p ${{ env.DOWNLOAD_PATH }}

        capability_hash=$(echo "${CAPABILITY_NAMES}" | tr ',' '\n' | sort | sha256sum | cut -d ' ' -f 1)
        cache_key="${CRE_CLI_VERSION}-${CAPABILITY_VERSION}-${capability_hash}"
        echo "cache-key=${cache_key}" | tee -a "${GITHUB_OUTPUT}"

    - name: Restore Cache CRE CLI
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        key: ${{ steps.setup-cache-dir-key.outputs.cache_key }}
        path: ${{ env.DOWNLOAD_PATH }}

    - name: Setup GitHub token using GATI
      if: ${{ cache-restore.outputs.cache-hit != 'true' }}
      id: setup-gati-token
      uses: smartcontractkit/.github/actions/setup-github-token@setup-github-token/v1
      with:
        aws-role-arn: ${{ inputs.gati-role-arn }}
        aws-lambda-url: ${{ inputs.gati-lambda-url }}
        aws-region: ${{ inputs.gati-region }}
        aws-role-duration-seconds: "1800"

    - name: Download test dependencies
      if: ${{ cache-restore.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: system-tests/tests/smoke/cre/cmd
      env:
        GITHUB_API_TOKEN: ${{ steps.setup-gati-token.outputs.access-token }}
        MAX_RETRIES: 3
        CRE_CLI_VERSION: ${{ inputs.cre-cli-version }}
        CAPABILITY_NAMES: ${{ inputs.capability-names }}
        CAPABILITY_VERSION: ${{ inputs.capability-version }}
        DOWNLOAD_PATH: ${{ env.DOWNLOAD_PATH }}
      run: |
        ./download_cre_ci_deps.sh \
          ${MAX_RETRIES} \
          ${CRE_CLI_VERSION} \
          ${CAPABILITY_NAMES} \
          ${CAPABILITY_VERSION} \
          ${DOWNLOAD_PATH}

    - name: Save cache
      if: ${{ cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.setup-cache-dir-key.outputs.cache_key }}
        path: ${{ env.DOWNLOAD_PATH }}

    - name: Move binaries to expected location
      shell: bash
      run: |
        echo "Moving binaries from ${{ env.DOWNLOAD_PATH }}/ to ${{ env.EXPECTED_PATH }}/"

        echo "Contents of ${{ env.DOWNLOAD_PATH }}/ before moving:"
        ls -la ${{ env.DOWNLOAD_PATH }}/

        mv ${{ env.DOWNLOAD_PATH }}/* ${{ env.EXPECTED_PATH }}/

        echo "Contents of ${{ env.EXPECTED_PATH }}/ after moving:"
        ls -la ${{ env.EXPECTED_PATH }}/
