// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package ccip_router

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ON RAMP FLOW
// The method name needs to be ccip_send with Anchor encoding.
// This function is called by the CCIP Sender Contract (or final user) to send a message to the CCIP Router.
// The size limit of data is 256 bytes.
// The message is sent to the receiver on the destination chain selector.
// This message emits the event CCIPSendRequested with all the necessary data to be retrieved by the OffChain Code
type CcipSend struct {
	DestChainSelector *uint64
	Message           *Solana2AnyMessage

	// [0] = [] config
	//
	// [1] = [WRITE] chainState
	//
	// [2] = [WRITE] nonce
	//
	// [3] = [WRITE, SIGNER] authority
	//
	// [4] = [] systemProgram
	//
	// [5] = [WRITE] tokenPoolsSigner
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewCcipSendInstructionBuilder creates a new `CcipSend` instruction builder.
func NewCcipSendInstructionBuilder() *CcipSend {
	nd := &CcipSend{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetDestChainSelector sets the "destChainSelector" parameter.
func (inst *CcipSend) SetDestChainSelector(destChainSelector uint64) *CcipSend {
	inst.DestChainSelector = &destChainSelector
	return inst
}

// SetMessage sets the "message" parameter.
func (inst *CcipSend) SetMessage(message Solana2AnyMessage) *CcipSend {
	inst.Message = &message
	return inst
}

// SetConfigAccount sets the "config" account.
func (inst *CcipSend) SetConfigAccount(config ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(config)
	return inst
}

// GetConfigAccount gets the "config" account.
func (inst *CcipSend) GetConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetChainStateAccount sets the "chainState" account.
func (inst *CcipSend) SetChainStateAccount(chainState ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(chainState).WRITE()
	return inst
}

// GetChainStateAccount gets the "chainState" account.
func (inst *CcipSend) GetChainStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetNonceAccount sets the "nonce" account.
func (inst *CcipSend) SetNonceAccount(nonce ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(nonce).WRITE()
	return inst
}

// GetNonceAccount gets the "nonce" account.
func (inst *CcipSend) GetNonceAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetAuthorityAccount sets the "authority" account.
func (inst *CcipSend) SetAuthorityAccount(authority ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority).WRITE().SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *CcipSend) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CcipSend) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CcipSend) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

// SetTokenPoolsSignerAccount sets the "tokenPoolsSigner" account.
func (inst *CcipSend) SetTokenPoolsSignerAccount(tokenPoolsSigner ag_solanago.PublicKey) *CcipSend {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenPoolsSigner).WRITE()
	return inst
}

// GetTokenPoolsSignerAccount gets the "tokenPoolsSigner" account.
func (inst *CcipSend) GetTokenPoolsSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[5]
}

func (inst CcipSend) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CcipSend,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CcipSend) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CcipSend) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.DestChainSelector == nil {
			return errors.New("DestChainSelector parameter is not set")
		}
		if inst.Message == nil {
			return errors.New("Message parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Config is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.ChainState is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Nonce is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenPoolsSigner is not set")
		}
	}
	return nil
}

func (inst *CcipSend) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CcipSend")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("DestChainSelector", *inst.DestChainSelector))
						paramsBranch.Child(ag_format.Param("          Message", *inst.Message))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          config", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("      chainState", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("           nonce", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("       authority", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("   systemProgram", inst.AccountMetaSlice[4]))
						accountsBranch.Child(ag_format.Meta("tokenPoolsSigner", inst.AccountMetaSlice[5]))
					})
				})
		})
}

func (obj CcipSend) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `DestChainSelector` param:
	err = encoder.Encode(obj.DestChainSelector)
	if err != nil {
		return err
	}
	// Serialize `Message` param:
	err = encoder.Encode(obj.Message)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CcipSend) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `DestChainSelector`:
	err = decoder.Decode(&obj.DestChainSelector)
	if err != nil {
		return err
	}
	// Deserialize `Message`:
	err = decoder.Decode(&obj.Message)
	if err != nil {
		return err
	}
	return nil
}

// NewCcipSendInstruction declares a new CcipSend instruction with the provided parameters and accounts.
func NewCcipSendInstruction(
	// Parameters:
	destChainSelector uint64,
	message Solana2AnyMessage,
	// Accounts:
	config ag_solanago.PublicKey,
	chainState ag_solanago.PublicKey,
	nonce ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenPoolsSigner ag_solanago.PublicKey) *CcipSend {
	return NewCcipSendInstructionBuilder().
		SetDestChainSelector(destChainSelector).
		SetMessage(message).
		SetConfigAccount(config).
		SetChainStateAccount(chainState).
		SetNonceAccount(nonce).
		SetAuthorityAccount(authority).
		SetSystemProgramAccount(systemProgram).
		SetTokenPoolsSignerAccount(tokenPoolsSigner)
}
