// This is the Collapsed Router Program for CCIP.
// As it's upgradable persisting the same program id, there is no need to have an indirection of a Proxy Program.
// This Router handles both the OnRamp and OffRamp flow of the CCIP Messages.
// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package ccip_router

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "CcipRouter"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	// The initialization is responsibility of Admin, nothing more than calling this method should be done first.
	Instruction_Initialize = ag_binary.TypeID([8]byte{175, 175, 109, 31, 13, 152, 155, 237})

	Instruction_TransferOwnership = ag_binary.TypeID([8]byte{65, 177, 215, 73, 53, 45, 99, 47})

	Instruction_AcceptOwnership = ag_binary.TypeID([8]byte{172, 23, 43, 13, 238, 213, 85, 150})

	// The Admin needs to add any new chain supported (this means both OnRamp and OffRamp).
	Instruction_AddChainSelector = ag_binary.TypeID([8]byte{28, 60, 171, 0, 195, 113, 56, 7})

	// The Admin is the only one able to enable or disable the chain selector
	Instruction_DisableChainSelector = ag_binary.TypeID([8]byte{24, 245, 159, 178, 139, 200, 133, 218})

	// The Admin is the only one able to enable or disable the chain selector
	Instruction_EnableChainSelector = ag_binary.TypeID([8]byte{29, 175, 195, 14, 137, 66, 194, 25})

	// The Admin can update the configuration of the Router, in this case the Solana Chain Selector
	Instruction_UpdateSolanaChainSelector = ag_binary.TypeID([8]byte{128, 198, 143, 222, 43, 55, 119, 106})

	// The Admin can update the configuration of the Router, in this case the Default Gas Limit
	Instruction_UpdateDefaultGasLimit = ag_binary.TypeID([8]byte{201, 34, 231, 229, 247, 252, 77, 210})

	// The Admin can update the configuration of the Router, in this case the Default Allow Out Of Order Execution (True/False)
	Instruction_UpdateDefaultAllowOutOfOrderExecution = ag_binary.TypeID([8]byte{44, 54, 136, 71, 177, 17, 18, 241})

	// The Admin can update the configuration of the Router, in this case the Enable Manual Execution After
	Instruction_UpdateEnableManualExecutionAfter = ag_binary.TypeID([8]byte{157, 236, 73, 92, 84, 197, 152, 105})

	// The CCIP Admin or the Mint Authority of the Token can register the Token Admin Registry
	Instruction_RegisterTokenAdminRegistryViaGetCcipAdmin = ag_binary.TypeID([8]byte{46, 246, 21, 58, 175, 69, 40, 202})

	// The Token's mint_authority can register themselves to the Token Admin Registry
	Instruction_RegisterTokenAdminRegistryViaOwner = ag_binary.TypeID([8]byte{85, 191, 10, 113, 134, 138, 144, 16})

	// The administrator of the token can setup the token pool
	Instruction_SetPool = ag_binary.TypeID([8]byte{119, 30, 14, 180, 115, 225, 167, 238})

	// The Admin can transfer the Admin Role of the Token Admin Registry
	Instruction_TransferAdminRoleTokenAdminRegistry = ag_binary.TypeID([8]byte{178, 98, 203, 181, 203, 107, 106, 14})

	// The Pending Admin can accept the Admin Role of the Token Admin Registry
	Instruction_AcceptAdminRoleTokenAdminRegistry = ag_binary.TypeID([8]byte{106, 240, 16, 173, 137, 213, 163, 246})

	Instruction_SetTokenBilling = ag_binary.TypeID([8]byte{225, 230, 37, 71, 131, 209, 54, 230})

	Instruction_SetOcrConfig = ag_binary.TypeID([8]byte{4, 131, 107, 110, 250, 158, 244, 200})

	// ON RAMP FLOW
	// The method name needs to be ccip_send with Anchor encoding.
	// This function is called by the CCIP Sender Contract (or final user) to send a message to the CCIP Router.
	// The size limit of data is 256 bytes.
	// The message is sent to the receiver on the destination chain selector.
	// This message emits the event CCIPSendRequested with all the necessary data to be retrieved by the OffChain Code
	Instruction_CcipSend = ag_binary.TypeID([8]byte{108, 216, 134, 191, 249, 234, 33, 84})

	// OFF RAMP FLOW
	//
	// The method name needs to be commit with Anchor encoding.
	//
	// This function is called by the OffChain when committing one Report to the Solana Router.
	// In this Flow only one report is sent, the Commit Report. This is different as EVM does,
	// this is because here all the chain state is stored in one account per Merkle Tree Root.
	// So, to avoid having to send a dynamic size array of accounts, in this message only one Commit Report Account is sent.
	// This message validates the signatures of the report and stores the Merkle Root in the Commit Report Account.
	// The Report must contain an interval of messages, and the min of them must be the next sequence number expected.
	// The max size of the interval is 64.
	// This message emits two events: CommitReportAccepted and Transmitted.
	Instruction_Commit = ag_binary.TypeID([8]byte{223, 140, 142, 165, 229, 208, 156, 74})

	// OFF RAMP FLOW
	//
	// The method name needs to be execute with Anchor encoding.
	//
	// This function is called by the OffChain when executing one Report to the Solana Router.
	// In this Flow only one message is sent, the Execution Report. This is different as EVM does,
	// this is because there is no try/catch mechanism to allow batch execution.
	// This message validates that the Merkle Tree Proof of the given message is correct and is stored in the Commit Report Account.
	// The message must be untouched to be executed.
	// This message emits the event ExecutionStateChanged with the new state of the message.
	// Finally, executes the CPI instruction to the receiver program in the ccip_receive message.
	Instruction_Execute = ag_binary.TypeID([8]byte{130, 221, 242, 154, 13, 193, 189, 29})

	// When a message is not being executed, then the user can trigger the execution manually.
	// No verification over the transmitter, but the message needs to be in some commit report.
	Instruction_ManuallyExecute = ag_binary.TypeID([8]byte{238, 219, 224, 11, 226, 248, 47, 192})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_Initialize:
		return "Initialize"
	case Instruction_TransferOwnership:
		return "TransferOwnership"
	case Instruction_AcceptOwnership:
		return "AcceptOwnership"
	case Instruction_AddChainSelector:
		return "AddChainSelector"
	case Instruction_DisableChainSelector:
		return "DisableChainSelector"
	case Instruction_EnableChainSelector:
		return "EnableChainSelector"
	case Instruction_UpdateSolanaChainSelector:
		return "UpdateSolanaChainSelector"
	case Instruction_UpdateDefaultGasLimit:
		return "UpdateDefaultGasLimit"
	case Instruction_UpdateDefaultAllowOutOfOrderExecution:
		return "UpdateDefaultAllowOutOfOrderExecution"
	case Instruction_UpdateEnableManualExecutionAfter:
		return "UpdateEnableManualExecutionAfter"
	case Instruction_RegisterTokenAdminRegistryViaGetCcipAdmin:
		return "RegisterTokenAdminRegistryViaGetCcipAdmin"
	case Instruction_RegisterTokenAdminRegistryViaOwner:
		return "RegisterTokenAdminRegistryViaOwner"
	case Instruction_SetPool:
		return "SetPool"
	case Instruction_TransferAdminRoleTokenAdminRegistry:
		return "TransferAdminRoleTokenAdminRegistry"
	case Instruction_AcceptAdminRoleTokenAdminRegistry:
		return "AcceptAdminRoleTokenAdminRegistry"
	case Instruction_SetTokenBilling:
		return "SetTokenBilling"
	case Instruction_SetOcrConfig:
		return "SetOcrConfig"
	case Instruction_CcipSend:
		return "CcipSend"
	case Instruction_Commit:
		return "Commit"
	case Instruction_Execute:
		return "Execute"
	case Instruction_ManuallyExecute:
		return "ManuallyExecute"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"initialize", (*Initialize)(nil),
		},
		{
			"transfer_ownership", (*TransferOwnership)(nil),
		},
		{
			"accept_ownership", (*AcceptOwnership)(nil),
		},
		{
			"add_chain_selector", (*AddChainSelector)(nil),
		},
		{
			"disable_chain_selector", (*DisableChainSelector)(nil),
		},
		{
			"enable_chain_selector", (*EnableChainSelector)(nil),
		},
		{
			"update_solana_chain_selector", (*UpdateSolanaChainSelector)(nil),
		},
		{
			"update_default_gas_limit", (*UpdateDefaultGasLimit)(nil),
		},
		{
			"update_default_allow_out_of_order_execution", (*UpdateDefaultAllowOutOfOrderExecution)(nil),
		},
		{
			"update_enable_manual_execution_after", (*UpdateEnableManualExecutionAfter)(nil),
		},
		{
			"register_token_admin_registry_via_get_ccip_admin", (*RegisterTokenAdminRegistryViaGetCcipAdmin)(nil),
		},
		{
			"register_token_admin_registry_via_owner", (*RegisterTokenAdminRegistryViaOwner)(nil),
		},
		{
			"set_pool", (*SetPool)(nil),
		},
		{
			"transfer_admin_role_token_admin_registry", (*TransferAdminRoleTokenAdminRegistry)(nil),
		},
		{
			"accept_admin_role_token_admin_registry", (*AcceptAdminRoleTokenAdminRegistry)(nil),
		},
		{
			"set_token_billing", (*SetTokenBilling)(nil),
		},
		{
			"set_ocr_config", (*SetOcrConfig)(nil),
		},
		{
			"ccip_send", (*CcipSend)(nil),
		},
		{
			"commit", (*Commit)(nil),
		},
		{
			"execute", (*Execute)(nil),
		},
		{
			"manually_execute", (*ManuallyExecute)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
